### ISSUE TITLE
Extract /security packages to go-mod-secrets

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/go-mod-bootstrap#12]
As directed in December 12th #security group conversation:

![image](https://user-images.githubusercontent.com/464327/70910447-5a32df80-1fd5-11ea-87c0-91c071493612.png)

Requires working go-mod-bootstrap build; e.g. dependent upon completion of #13.

Will also require corresponding changes to https://github.com/edgexfoundry/edgex-go.

**Comment by AnthonyMBonafide** [comment]
Also, depends on https://github.com/edgexfoundry/go-mod-secrets/issues/43
