### ISSUE TITLE
[Secure Consul Ph. 2] Add glue logic to obtain Consul token and pass to go-mod-registry and go-mod-configuration

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/go-mod-bootstrap#124]
This is a subtask of implementation of secure bootstrapping ADR.

To enable Consul authentication it is necessary to obtain a consul token from the Vault consul secrets engine and use it to initialize go-mod-registry and go-mod-configuration in order to secure the communication with Consul.

The retrieving Consul tokens will be from files to avoid chicken-and-egg problem in go-mod-bootstrap and the location of files depends the completion of issue https://github.com/edgexfoundry/edgex-go/issues/3306 .

**Comment by jim-wang-intel** [comment]
call vault's consul/creds/service_key api and thus we need to have abstraction for that
