### ISSUE TITLE
LoggingClientFrom doesn't handle nil case properly

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/go-mod-bootstrap#128]
Commit https://github.com/edgexfoundry/go-mod-bootstrap/pull/125/commits/3651de7107942df3a5e0279978d810b602da9220 revised bootstrap.go to DI get the logging client first as opposed to directly creating a Stdout logging client.  However, the logic inside `LoggingClientFrom` (https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/bootstrap/container/logging.go#L28) doesn't deal with nil case and will result in `panic:  interface conversion: interface is nil, not logger.LoggingClient`.  Please kindly consider to use similar logic from `RegistryFrom` to handle nil case as shown below:
```
func LoggingClientFrom(get di.Get) logger.LoggingClient {
	loggingClient := get(LoggingClientInterfaceName)
	if loggingClient != nil {
		return loggingClient.(logger.LoggingClient)
	}
	return (logger.LoggingClient)(nil)
}
```

**Comment by cloudxxx8** [comment]
fixed by #129
