### ISSUE TITLE
Tests should run cleanly when passed the -race option

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/go-mod-bootstrap#15]
To ensure our tests (and to some extent production code) are reliable, we should be running unit tests with the -race argument in the Makefile.  Ensure tests go green with -race option.  Add -race to the test target in our Makefile.

Dependent upon completion of #13.

**Comment by brandonforster** [comment]
Per discussion on DevOps WG call on 27 February, this has been rescoped from Geneva to Hanoi so that DevOps can address some underlying build concerns.

**Comment by jpwhitemn** [comment]
DevOps addressed
