### ISSUE TITLE
[Secure Consul Ph. 3] Implement Consul token refreshing/renewal mechanism

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/go-mod-bootstrap#176]
Once the consul's TTL has been reduced to some expiring TTL per Consul token (i.e. this issue from `edgex-go` has been implemented: https://github.com/edgexfoundry/edgex-go/issues/3258), we need to add `Consul token` renewal logic when the token is obtained or accessed.

Token freshness can be pre-checked by a request made to `/acl/token/self`

Depends on: https://github.com/edgexfoundry/edgex-go/issues/3258

**Comment by lenny-intel** [comment]
@jim-wang-intel , is this still needed since the TTL is now based on the service Vault token which is already being refreshed?

**Comment by jim-wang-intel** [comment]
@lenny-intel right, we don't need this any more as the TTL of Consul is totally based on that of Vault token and cannot be greater than that. So this issue is closed.
