### ISSUE TITLE
Remove the dependency of github.com/BurntSushi/toml

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-bootstrap#208]
In go.mod, there are two toml related libraries: github.com/BurntSushi/toml and github.com/pelletier/go-toml
I believe we can use only one.

In https://github.com/BurntSushi/toml, it states **THIS PROJECT IS UNMAINTAINED**

**Comment by lenny-intel** [comment]
Agreed, I just verified that the one location we use `BurntSushi/toml` can be replaced with using `pelletier/go-toml`  to un-marshal the contents of the TOML file. I run a full execution test to verify.
