### ISSUE TITLE
Enable CORS access to EdgeX microservices

### ISSUE THREAD

**Issue by magallardo** [edgexfoundry/go-mod-bootstrap#281]
Hello,

# 🚀 Feature Request

### Relevant Package
This feature request is for the API Gateway

### Description
The Edgex components are exposed through REST APIs and those services are usually called from a UI running on a browser.  Most browser prevent calls to services at a different origin (CORS) thus making it difficult the interactions with services like Edgex.
There are basically 2 ways to solve the CORS issue.  The first one is on the client side (UI application) by using a proxy server.  Unfortunately this solution is static and need to know before hand the back end servers.
The second option is to enable the backend server to allow CORS.

### Describe the solution you'd like
Currently I have been bypassing this issue by using a proxy server at the client site.  However, this solution is not working due to the nature of IoT projects and solutions.  The IoT solutions tend to be very dynamic and in my specific example, the number of instances where the Edgex framework is deployed is dynamic and can change.  That makes the proxy option irrelevant as that solution is static.

So, the preferred solution will be to allow the user to enable/disable CORS as desired on the API Gateway.  That will allow calling the API from UI clients without requiring to use a proxy.

### Describe alternatives you've considered
As described above, I am already using a proxy solution but it only works for a static number of Edgex installations.

Thanks in advance,
Marcelo

**Comment by cloudxxx8** [comment]
it's not hard to add this implementation, but we need more time to test it manually
according to the current test infrastructure, we can't add automation tests for this because it needs multiple machines

**Comment by bnevis-i** [comment]
Waiting for https://github.com/edgexfoundry/edgex-docs/issues/608

**Comment by jpwhitemn** [comment]
Issue has been resolved, but believe just Docs work to be done.  Per TSC 11/10/21 - close this
