### ISSUE TITLE
Missing Telemetry configuration cause backward breaking change

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-bootstrap#332]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
App Services at this point

### Is this a regression?

If custom app service doesn't add the new Telemetry config section the service will fail during bootstrap

### Description and Minimal Reproduction [**REQUIRED**]
Run ASC with a profile w/o the new Telemetry section

## 🔥 Exception or Error
Telemetry interval is invalid time duration: time: invalid duration \"\""

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**
Just need to default the Interval to "0s" (disable  reporting) when it is blank just before Paring the value here:
https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/bootstrap/handlers/metrics.go#L53

**Comment by farshidtz** [comment]
Same error in core-data, when upgrading from an older version (Jakarta) that doesn't have the telemetry internal in the config files:
```
2022-05-02T15:11:54+02:00 edgexfoundry.core-data[11607]: level=ERROR ts=2022-05-02T13:11:54.933311866Z app=core-data source=metrics.go:55 msg="Telemetry interval is invalid time duration: time: invalid duration \"\""
```

**Comment by cloudxxx8** [comment]
edgex-go just upgraded and rebuilt 5 hours ago
