### ISSUE TITLE
Add GetSecretWithRetry() to SecretProvider

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-bootstrap#343]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
SecretProvider

### Description [**REQUIRED**]
Many Device and App services have code to retry on getting their needed secrets for allowing time for user to push needed secrets into Vault via the service's /secret endpoint.

### Describe the solution you'd like
Add the GetSecretWithRetry() API which is the same as GetSecret(), but adds the  retry and wait duration parameters.
Implementation will retry if the 404 (not fond) error is returned until the secret is found or retry duration is exceeded.

### Describe alternatives you've considered
each service implement this same retry code.

**Comment by bnevis-i** [comment]
This is obsoleted potentially by the ability to register a handler when a secret is added/changed.  Moving to icebox.

**Comment by bnevis-i** [comment]
@lenny-intel, @ajcasagrande    Is this feature still needed?

**Comment by ajcasagrande** [comment]
I don't think so

**Comment by bnevis-i** [comment]
Closing the issue as will-not-fix.  Reopen if needed in the future.
