### ISSUE TITLE
Add HasSecret function to SecretProvider

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/go-mod-bootstrap#350]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

go-mod-bootstrap SecretProvider interface

### Description [**REQUIRED**]
Calling `GetSecret(...)` requires you to provide the secret fields (or leave blank to retrieve all), and returns the values which you then ignore, just to determine if a specified secret path exists or not.

### Describe the solution you'd like
It was a bit hard to choose the return type, as typically you would expect `bool`, however there is the possibility that the SecretStore cannot be reached, so you would need an `error` return as well, so `(bool, error)`. That seemed a bit redundant. Given the way that the `GetSecret` returns an error as well for non-existent keys, I felt it made sense to make it consistent with that: 

```go
type SecretProvider interface {
	...

	// HasSecret checks whether the service's SecretStore contains a secret at the specified path. If error is nil, the secret path exists.
	HasSecret(path string) error
}
```

### Describe alternatives you've considered
- Calling `GetSecret` and ignoring the returned values
- Using the list all feature of #348 and checking if it is in there (though this is inefficient as well)

**Comment by lenny-intel** [comment]
@ajcasagrande , What is the use case for needing this?

**Comment by bnevis-i** [comment]
It's philsophical.  We could check if the error returned from the secret store was a 401 (unauthorized) or a 404 (not found).  Personally, if no error but missing is a valid return case a lot of the time I wouldn't use an error for that.

**Comment by ajcasagrande** [comment]
@lenny-intel this is the WIP code that made me think of it:

https://github.com/ajcasagrande/device-onvif-camera/blob/78832236273aa772dbc31dce0d22da37e28a7617/internal/driver/macmapper.go#L40-L44

```go
	credsMap := make(map[string]string)
	for secretPath, macs := range raw {
		if _, err := sdk.RunningService().SecretProvider.GetSecret(secretPath, secret.UsernameKey); err != nil {
			lc.Warnf("One or more MAC address mappings exist for the secret path '%s' which does not exist in the Secret Store!", secretPath)
		}
```

**Comment by bnevis-i** [comment]
Above doesn't really distinguish between the secret store being broken vs the secret not being there.

**Comment by lenny-intel** [comment]
> this is the WIP code that made me think of it:
@ajcasagrande , got it.
