### ISSUE TITLE
Convert config key names `authmode` and `secretname` to upper camel case

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/go-mod-bootstrap#352]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 go-mod-bootstrap messaging

### Description [**REQUIRED**]
 
The configuration key names `authmode` and `secretname` are defined in go-mod-bootstrap:
https://github.com/edgexfoundry/go-mod-bootstrap/blob/cfb3e675d067e751fbbb5b08f60e7b21f51c3f19/bootstrap/messaging/messaging.go#L34-L35

app-functions-sdk-go uses these two keys to look up the values of authmode and secretname from the 
MessageBusConfig map:
https://github.com/edgexfoundry/app-functions-sdk-go/blob/e0accd9328fdd6e1df10535226a15790ead6a2cf/internal/trigger/messagebus/messaging.go#L282-L288

This results in the config key names in app-service configuration file must also be lowercase, which is inconsistent with the naming convention for other configuration keys.
https://github.com/edgexfoundry/app-service-configurable/blob/354093ed76bafc9ccf1014354cec2dcad1025761/res/sample/configuration.toml#L268-L281

### Describe the solution you'd like
 
Convert `authmode` and `secretname` to upper camel case.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bnevis-i** [comment]
2/1/23: Revisit to see if this is still valid.

**Comment by lenny-intel** [comment]
These constants are no longer use and need to be removed.
