### ISSUE TITLE
Redact the logging of Insecure Secrets when env override is used

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/go-mod-bootstrap#366]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

this repo and any other repo that uses InsecureSecrets

### Description [**REQUIRED**]
Right now, you can override the value of an Insecure Secret via an ENV override; however, this causes it to printed out in plain text in the log files.

```
source=config.go:391 msg="Loaded service configuration from ./res/configuration.toml"
source=variables.go:352 msg="Variables override of 'Writable.InsecureSecrets.credentials001.Secrets.password' by environment variable: WRITABLE_INSECURESECRETS_CREDENTIALS001_SECRETS_PASSWORD=admin"
source=variables.go:352 msg="Variables override of 'Writable.InsecureSecrets.credentials001.Secrets.username' by environment variable: WRITABLE_INSECURESECRETS_CREDENTIALS001_SECRETS_USERNAME=admin"
```

### Describe the solution you'd like
Print the env override to alert the user of its presence, but redact the value of anything under the `Writable.InsecureSecrets` structure.

```
source=config.go:391 msg="Loaded service configuration from ./res/configuration.toml"
source=variables.go:352 msg="Variables override of 'Writable.InsecureSecrets.credentials001.Secrets.password' by environment variable: WRITABLE_INSECURESECRETS_CREDENTIALS001_SECRETS_PASSWORD=<redacted>"
source=variables.go:352 msg="Variables override of 'Writable.InsecureSecrets.credentials001.Secrets.username' by environment variable: WRITABLE_INSECURESECRETS_CREDENTIALS001_SECRETS_USERNAME=<redacted>"
```

### Describe alternatives you've considered
Not using env overrides by creating a new configuration.toml and compiling it into docker image or volume mounting it.

**Comment by lenny-intel** [comment]
@bnevis-i FYI.

**Comment by ajcasagrande** [comment]
I can work on this. I have some code already written, and working on the unit tests. One thing I just noticed though, is that the `logger.MockLogger` is not a `mock.Mock` and therefore cannot be inspected as easily.
