### ISSUE TITLE
Add general security service metrics

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-bootstrap#374]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for SecretProvider and 

### Description [**REQUIRED**]
Add agreed upon Security Service Metrics that all services will inherit. 

### Describe the solution you'd like
Each metric name will be prefix with `Security` which allows them to be enable/disable in bulk. i.e. `Security = true` or individually `SecuritySecretsRequested = true` , `SecuritySecretsStored = true` 

Aggreged upon Security Service Metris are: 

- [x] Counter - secret requested from the store (**SecuritySecretsRequested**) ---- **DONE**
- [x] Counter - consul token requested (**SecurityConsulTokensRequested**)
- [x] Counter - put secret (**SecuritySecretsStored**) ---- **DONE**
- [ ] Timer - how long to obtain secret token (**SecuritySecretTokenDuration**)
- [x] Timer - how long to obtain consul token (**SecurityConsulTokenDuration**)

This issue will be used for multiple PRs to implement the above list. Check off each metric once they are implemented. 

Code must be robust in respect to the **MessageBus** and **MetricsManager** dependencies so not to break the services that don't include them in their bootstrapping yet. App and Device services have the proper bootstrapping, but not all the Core and Support services do. The security services use bootstrapping but will not implement service metrics and thus must not be impacted. Separate PR(s) will be added to edgex-go to add the proper bootstrapping to those Core/Support services that are missing it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bnevis-i** [comment]
Moving to backlog as focusing on breaking changes right now.
