### ISSUE TITLE
Remove add config version for stem

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-bootstrap#400]
# 🚀 Refactor Request

### Relevant Package [**REQUIRED**]

 This feature request is for config version in Config Provider path

### Description [**REQUIRED**]
 Needs to be v3  which is now in the default stem

### Describe the solution you'd like
 Remove local constant and don't add version

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
since we won't change the version number to 3.1 or 3.2 in config, I propose to use **v3** instead of **3.0**

**Comment by lenny-intel** [comment]
> since we won't change the version number to 3.1 or 3.2 in config, I propose to use **v3** instead of **3.0**

Agreed. Changed in core contracts PR and description above.
