### ISSUE TITLE
The env overridden config doesn't apply to the Configuration Provider.

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/go-mod-bootstrap#457]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in go-mod-bootstrap

### Is this a regression?

No

### Description and Minimal Reproduction [**REQUIRED**]

Use Configuration Provider and run the service with environment variable override.

1. The service load config from the configuration.toml
2. The service push config to Configuration Provider
3. The service overrides the config by the environment variable

```
$ docker logs edgex-app-sample -f
level=INFO ts=2023-03-03T08:25:58.241676792Z app=app-<profile> source=service.go:490 msg="Starting app-sample 3.0.0-dev.20 "
level=INFO ts=2023-03-03T08:25:58.244133706Z app=app-sample source=config.go:311 msg="Using Configuration Provider access token of length 0"
...
level=INFO ts=2023-03-03T08:26:01.057553795Z app=app-sample source=config.go:502 msg="Loaded private configuration from ./res/sample/configuration.toml"
level=INFO ts=2023-03-03T08:26:01.058068702Z app=app-sample source=config.go:176 msg="Using local private configuration from file"
level=INFO ts=2023-03-03T08:26:01.630028337Z app=app-sample source=config.go:185 msg="Configuration has been pushed to into Configuration Provider"
level=INFO ts=2023-03-03T08:26:01.636655873Z app=app-sample source=variables.go:377 msg="Variables override of 'MessageBus.Host' by environment variable: MESSAGEBUS_HOST=edgex-mqtt-broker"
level=INFO ts=2023-03-03T08:26:01.636686111Z app=app-sample source=variables.go:377 msg="Variables override of 'MessageBus.Port' by environment variable: MESSAGEBUS_PORT=1883"
...
```

We expect the service should put the overridden config to the Configuration Provider but it didn't.

## 🌍  Your Environment
**Deployment Environment:**

Main branch

**Anything else relevant?**

**Comment by weichou1229** [comment]
@ejlee3 Could you help check this issue? 
This issue might be caused by the PR https://github.com/edgexfoundry/go-mod-bootstrap/pull/426/files#diff-5346c73553fe1e8350deb1a29ed066b1202c1ea35e57d206adbb6f359ed1d299L191-L207

**Comment by lenny-intel** [comment]
Per the Common Config ADR, overrides are no longer push into Configuration Provider. See here: https://docs.edgexfoundry.org/3.0/design/adr/0026-Common%20Configuration/#considerations

Override are applied after the settings are pushed/pulled to/from the Configuration Provider.

@cloudxxx8 , If we need to revisit this please put it on the agenda for the next Core WG.

**Comment by weichou1229** [comment]
@lenny-intel 
> Override are applied after the settings are pushed/pulled to/from the Configuration Provider.

Thanks for your reply, is it means we should not use the env variable override if we use Configuration Provider?

For the test case on the edgex-taf,
- it override an app service config by env `WRITABLE_PIPELINE_FUNCTIONS_HTTPEXPORT_PARAMETERS_URL` from the docker-compose file
- After deploying the app service, it changes config HttpExportSize to true from the Consul
- then the app service pulls the changes from the Consul
- and the app service update `HttpExportSize` and also updates the `Writable.Pipeline.Functions.HTTPExport.Parameters.Url`

**Comment by lenny-intel** [comment]
@weichou1229 , nope. Env overrides end result for the services is then same. They just get applied after all the configuration is loaded from file or config provider, not before. The only change with respect to the override values is they are not pushed into the config provider. As I mentioned above, we still have time to reconsider this `not pushing` overrides into the config provider.

**Comment by cloudxxx8** [comment]
Let's discuss this issue in the Core WG meeting.
I think the main issue is that one of the Writable config change would cause the whole Writable section update at runtime, and it will override all the Writable configs defined in the environment variable.
Users might encounter the following situation:

- They define five environment variables to override 5 different configs value under Writable
- Users change log level from Consul, and all the Writable configs are changed at runtime
- The five environment variables settings become ineffective until the service is restarted

This issue cannot be resolved by pushing environment variables to the config provider.

**Comment by lenny-intel** [comment]
@cloudxxx8 , yes I think we need to revisit this Core WG meeting and then follow-up in TSC if we recommend changing current implementation.

Note, Writable updates are one setting, not the complete Writable section. So only the single setting that has an env override will be impacted.

**Comment by cloudxxx8** [comment]
Decided in Core WG meeting 08-March-2023, keeping the new design in 3.0, not pushing environment variable override to the Configuration Provider.
opened https://github.com/edgexfoundry/go-mod-bootstrap/issues/464 to fix the test cases
