### ISSUE TITLE
The Writable config mechanism should not change the whole writable section

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-bootstrap#464]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for all

### Description [**REQUIRED**]
The current config provider contains a mechenism to monitor the config changes under the Writable section at runtime.
However, any single config change will cause the whole Writable section to be replaced.
This behavior will cause the following unexpected situation:
If some of the Writable config is defined in environment varialbe to override, such as `WRITABLE_PERSISTDATA: false`, and the user modify the log level from the config provider, the Writable.PersistData will be changed to the default value `true` at runtime.
https://github.com/edgexfoundry/edgex-go/blob/3ead8ec53459b72f62f51c7b78b8446db778950c/cmd/core-data/res/configuration.toml#L5

### Describe the solution you'd like
Bootstrap should only change the modified config from the config provider at runtime, not the whole Writable section.

**Comment by cloudxxx8** [comment]
@ejlee3 for awareness

**Comment by lenny-intel** [comment]
@ejlee3 , this is a side effect of not pushing the overrides into the Config Provider.

**Comment by lenny-intel** [comment]
@cloudxxx8 , I have asked for this to be a topic in this weeks Architects meeting. It is my opinion that the env override values should be pushed into the config provider as we previously have done.

**Comment by cloudxxx8** [comment]
If the envrionment variable is changed in the second starts up, should we push them again?

**Comment by lenny-intel** [comment]
> If the envrionment variable is changed in the second starts up, should we push them again?

Good question

**Comment by lenny-intel** [comment]
On hold until overrides are applied and pushed into Config Provider and verify that it resolves this issue.
