### ISSUE TITLE
Containers return typed nils when a service is not used instead of untyped nils

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/go-mod-bootstrap#50]
Because [the value returned by the service constructor always has a type](https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/bootstrap/bootstrap.go#L172) (even if it doesn't have a value) the resulting variable returned by the DIC [will never be evaluated to nil.](https://golang.org/doc/faq#nil_error). This has the knock on effect of causing things like [`RegstryFrom` to always execute the `!= nil` path](https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/bootstrap/container/registry.go#L29), causing any consuming services to have `registryClient != nil` to evaluate to `true` when it is a typed nil.

**Comment by michaelestrin** [comment]
FWIW this is by design.  The intention was to only retrieve an object from the DIC if that object actually exists.  What's the specific use case where the DIC contains a nil value for a specific object?

@brandonforster

**Comment by brandonforster** [comment]
Using local configuration in EdgeX Go and not using the registry, the code expects the `registryClient` retrieved from the DIC to be nil, but it is `(*interfaces.registryClient) nil` and does not evaluate to nil.

**Comment by michaelestrin** [comment]
It sounds like this is a variation on the pointer to a pointer to nil that we discussed recently in a different context.  

There's an example of how to access Registry from the DIC [here](https://github.com/edgexfoundry/go-mod-bootstrap/blob/004cb41dba56723f9737002d4f720b413c11e93c/bootstrap/container/registry.go#L27).

Searching through the code in master, I don't see a reference to `interfaces.registryClient`.  Can you point me towards the code you're referring to where this problem exists?

**Comment by brandonforster** [comment]
Closing, the problem was in some related code. This is fine.
