### ISSUE TITLE
Add dev command line flag to apply "Host" env overrides when running in hybrid mode

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-bootstrap#509]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Config processing

### Description [**REQUIRED**]
 Currently with the new Common Config, the common `Host` settings, i.e MessageBus.Host, etc.,  are in common config in the Config Provider. When running from command line in hybrid mode with Config Provider, the common `Host` settings have been overridden with the docker network names and are not valid when running service outside docker. 

The current work around is to have these common `Host` settings commented out every services' local private configuration file. When running the service in hybrid mode with Config Provider, the developer must uncomment these settings.

Example:
```yaml
# uncomment when running from command-line in hybrid mode with -cp -o flags
#Clients:
#  core-metadata: # Used for version check on start-up comes from Common Config
#      Host: "localhost"
#Registry:
#  Host: "localhost"
#Database:
#  Host: "localhost"

MessageBus:
#  Host: localhost # uncomment when running from command-line in hybrid mode
```
### Describe the solution you'd like
 Add the new `--hybrid` command flag which will enable Env Overriding of these `Host` settings when pulled from the Configuration Provider. This will be limited to only environment variables that end in `_HOST` so that it is not a end around to re-enable Env Overrides as highest precedence as is in V2.

### Describe alternatives you've considered
 Use current work around of commented out settings which clutter the service config files

**Comment by iain-anderson** [comment]
Could make it so that `--hybrid` explicitly overrides those settings to `localhost` without looking at the env vars?

**Comment by lenny-intel** [comment]
Yes, I was thinking the same thing. Kept it to just those known Host settings.

**Comment by cloudxxx8** [comment]
`--hypbrid` is not intiutive for the normal users.  I suggest using `--dev` for this and specify it's for the hybrid mode for development in the help text.
