### ISSUE TITLE
External MQTT Rename SecretPath to SecretName

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/go-mod-bootstrap#550]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Config

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Levski

### Description and Minimal Reproduction [**REQUIRED**]

- Run EdgeX 3.x in non-secure mode
- Modify the configuration of edgex-core-command via Consul to enable ExternalMQTT with the `usernamepassword` authentication mode:
  - Set ExternalMQTT.Enabled to `true`
  - Set ExternalMQTT.AuthMode to `usernamepassword`
- Restart edgex-core-command

## 🔥 Exception or Error
<pre><code>
level=ERROR ts=2023-05-31T10:33:19.103500932Z app=core-command source=externalmqtt.go:77 msg="Failed to retrieve secret data: Error, secretName () doesn't exist in secret store"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Docker

**EdgeX Version [**REQUIRED**]:** main 3.x

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@cherrycl please add related test for this issue in the next release
