### ISSUE TITLE
Move the common middleware functions to go-mod-bootstrap

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/go-mod-bootstrap#565]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

This feature request is for all of the EdgeX micro services have a dependency on it

### Description [**REQUIRED**]
Currently the common middleware functions (e.g., `ManageHeader`, `LoggingMiddleware`, `UrlDecodeMiddleware`) are defined and applied in the router of each EdgeX service separately as listed below:
- [core-command](https://github.com/edgexfoundry/edgex-go/blob/main/internal/core/command/router.go#L42-L44) and other services of edgex-go
- [device-sdk-go ](https://github.com/edgexfoundry/device-sdk-go/blob/main/internal/controller/http/restrouter.go#L70-L72)
- ...

### Describe the solution you'd like

The common middleware functions can be defined in the `go-mod-bootstrap` and be applied in the `CommonController` to avoid the re-declaration of the functions and among each EdgeX service.

#### Note
The issue needs https://github.com/edgexfoundry/go-mod-bootstrap/pull/557 to get merged first to avoid the code conflict.

**Comment by lenny-intel** [comment]
@cloudxxx8 , should this be closed by #562

**Comment by cloudxxx8** [comment]
No, #562 is for common API, not common middleware.  Lindsey means the following:
https://github.com/edgexfoundry/edgex-go/blob/54d035bfa974c800c1254128570959cbd1217788/internal/pkg/correlation/middleware.go

**Comment by lenny-intel** [comment]
OH, ok. missed the `middleware` part in the title... THX!
