### ISSUE TITLE
Update http handler functions and middleware to use general signature

### ISSUE THREAD

**Issue by lindseysimple** [edgexfoundry/go-mod-bootstrap#572]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for all of the EdgeX micro services have a dependency on it.

### Description [**REQUIRED**]
 
In the previous changes of [Replacement for Gorilla/MUX package](https://github.com/edgexfoundry/go-mod-bootstrap/issues/556) and [Move the common middleware functions to go-mod-bootstrap](https://github.com/edgexfoundry/go-mod-bootstrap/issues/565), changes have been made to modify the `http.HandlerFunc` and `func(http.ResponseWriter, *http.Request)` signatures to comply with the `echo.HandlerFunc` and `echo.MiddlewareFunc` signatures for the new `Echo` web framework.

### Describe the solution you'd like

Using the wrapper functions to wrap the `http.HandlerFunc` and `func(http.ResponseWriter, *http.Request)` signatures to `echo` signatures to provide more flexibility if switching to other web framework in the future.

The wrapper function are also useful for `device-sdk-go` service [interface](https://github.com/edgexfoundry/device-sdk-go/blob/main/pkg/interfaces/service.go#L128-L131) where the `HandlerFunc` is passed from the parent device service and we'd like to avoid breaking change to modify the signature of the two methods.
```
AddRoute(route string, handler func(http.ResponseWriter, *http.Request), methods ...string) error
AddCustomRoute(route string, authentication Authentication, handler func(http.ResponseWriter, *http.Request), methods ...string) error
```

**Comment by cloudxxx8** [comment]
clsoe this issue because we can't totally wrap echo handlers if it contains path param
