### ISSUE TITLE
CORS configuration isn't overriden by environment variable

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/go-mod-bootstrap#578]
# Question

### Affected Services [**REQUIRED**]

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Levski

### Description and Minimal Reproduction [**REQUIRED**]
1. Get compose file from [edgex-compose/docker-compose-no-secty.yml](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose-no-secty.yml)
2. Add `SERVICE_CORSCONFIGURATION_ENABLECORS: "true"` under `core-metadata/environment`
3. Deploy EdgeX by `docker compose -f docker-compose-no-secty.yml up -d`
4. GET http://localhost:59881/api/v3/config

## 🔥 Exception or Error
<pre><code>
....
"EnableCORS": false
....
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**
View the configuration under edgex/v3/core-metadata/service on Consul, no `CORSConfiguration` found

**Comment by lenny-intel** [comment]
@cherrycl, this is because the CORS configuration is now in Common Config and must be override their. Since it doesn't exist ion the service's private config, it can't be overridden on the service it's self. 

Other option is to added `Service.CORSConfiguration.EnableCORS` to the service's private config in Consul and restart the service.

**Comment by cloudxxx8** [comment]
@lenny-intel should the environment variable override search all the configs including the ones in common config?
in the current design, users can't use the environment variable override for any common config in an individual service, such as logging level.  Users might not want to enable the debug log for all the services.  The usable environment variables for individual service are very limited now.

**Comment by lenny-intel** [comment]
@cloudxxx8, 

> should the environment variable override search all the configs including the ones in common config?

Not possible, as it is the environment only for the service that is running. We have 3 options.
- Enabled CORS for all services via Common Config for all service via Env Override on core-common-config-bootstrapper
- Enable CORS for the specific service via Consul by dynamically adding `Service.CORSConfiguration.EnableCORS` for the service
- Add `Service.CORSConfiguration.EnableCORS` to each services private config file so it can be overridden as in previous release.

**Comment by jumpingliu** [comment]
per the  Core/QA WG meeting on Aug 16, we decide to modify the doc [here](https://docs.edgexfoundry.org/3.1/security/Ch-CORS-Settings/#enabling-cors-for-individual-microservices) based on Lenny's comments, so close this issue.
