### ISSUE TITLE
LoggingClient isn't updated correctly

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/go-mod-bootstrap#61]
The LoggingClient seems not updated correctly after loading configuration
https://github.com/edgexfoundry/go-mod-bootstrap/blob/e56334c0d91f0ff7de15cfca28b64fe2c0355652/bootstrap/bootstrap.go#L109

Maybe we should update the `Process` method with pointer receiver
https://github.com/edgexfoundry/go-mod-bootstrap/blob/e56334c0d91f0ff7de15cfca28b64fe2c0355652/bootstrap/config/config.go#L153

**Comment by lenny-intel** [comment]
@hahattan , nice catch! This has been fixed in #62
