### ISSUE TITLE
Flags parsing fails on specific values '-r' or '-cp'

### ISSUE THREAD

**Issue by adam-intel** [edgexfoundry/go-mod-bootstrap#78]
The flag parser will fail on arguments if the flag string contains '-r' or '--cp'.  This can happen if the following string is past to the executable:

`./some-device-service -confdir config/device-rest-go`

The '-r' in the word 'rest' will cause the parser to fail. 

https://github.com/edgexfoundry/go-mod-bootstrap/blob/e7263182f03795a80ecad393cb2c8c940050476c/bootstrap/flags/flags.go#L80

**Comment by lenny-intel** [comment]
Work around until this is addressed is to always use "="

```
./some-device-service -confdir=config/device-rest-go
```
